.DEFAULT_GOAL := help

.PHONY: help build build.watch compile_translations detect_changed_source_translations dummy_translations \
        extract_translations generate_translations pull_translations \
        requirements upgrade test validate_translations clean

NODE_BIN=$(CURDIR)/node_modules/.bin

THEME_NAME := src/edx_credentials_themes

# Generates a help message. Borrowed from https://github.com/pydanny/cookiecutter-djangopackage.
help: ## display this help message
	@echo "Please use \`make <target>\` where <target> is one of"
	@awk -F ':.*?## ' '/^[a-zA-Z]/ && NF==2 {printf "\033[36m  %-25s\033[0m %s\n", $$1, $$2}' $(MAKEFILE_LIST) | sort

build: ## compile SASS to CSS
	$(NODE_BIN)/webpack --config webpack.config.js --progress

build.watch: ## compile SASS to CSS and watch for changes
	$(NODE_BIN)/webpack --config webpack.config.js --progress --watch

requirements: ## Sync dev dependencies
	uv sync --group dev
	uv tool install tox --with tox-uv
	npm install

upgrade: ## Upgrade python dependencies and regenerate uv.lock
	uv run --with edx-lint edx_lint write_uv_constraints pyproject.toml
	uv lock --upgrade

test: ## Confirm compiled assets have not changed (SASS matches CSS)
	git diff --exit-code $(THEME_NAME)/ ":(exclude)$(THEME_NAME)/conf"

clean: ## Remove generated byte code and build artifacts
	find . -name '__pycache__' -exec rm -rf {} + 2>/dev/null || true
	find . -name '*.pyc' -exec rm -f {} +
	rm -rf build/ dist/ *.egg-info/ .pytest_cache/

compile_translations: ## compile translation files
	cd $(THEME_NAME) && i18n_tool generate

detect_changed_source_translations: ## detect changes in source translations
	cd $(THEME_NAME) && i18n_tool changed

dummy_translations: ## generate dummy translation files
	cd $(THEME_NAME) && i18n_tool dummy

extract_translations: ## extract strings to be translated, outputting .po files
	cd $(THEME_NAME) && i18n_tool extract --no-segment

generate_translations: extract_translations dummy_translations compile_translations

pull_translations: ## Pull translations via atlas
	# Remove existing translation directories
	find $(THEME_NAME)/conf/locale -mindepth 1 -maxdepth 1 -type d -exec rm -r {} \;
	atlas pull $(ATLAS_OPTIONS) \
	           translations/credentials-themes/edx_credentials_themes/conf/locale:$(THEME_NAME)/conf/locale
	make compile_translations

validate_translations: generate_translations detect_changed_source_translations ## validate translations
	cd $(THEME_NAME) && i18n_tool validate
