[tox]
envlist = django{42,52}
requires = tox-uv>=1

[testenv]
runner = uv-venv-lock-runner
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    django42: django42
    django52: test
allowlist_externals =
    make
