name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_call:

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.12']
        toxenv: [django42, django52]

    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Setup Nodejs
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: '.nvmrc'

      - name: Install uv
        uses: astral-sh/setup-uv@19b4d1e990bec64818914c40230bde93a0de300b # v9.0.0
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Install CI dependencies
        run: uv sync --group ci

      - name: Install system dependencies
        run: sudo apt install -y gettext

      - name: Run tox
        run: uv run tox -e ${{ matrix.toxenv }}
