name: CI

on:
  push:
    branches: [master]
  pull_request:
  workflow_call:

jobs:
  run_tests:
    name: ${{ matrix.toxenv }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ['3.12']
        toxenv: [django42, django52]

    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Nodejs
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: '.nvmrc'

      - name: Install uv
        uses: astral-sh/setup-uv@d269b9917d8e33f7165632f15cc38a13726f64b5 # v9.0.0
        with:
          enable-cache: true
          python-version: "${{ matrix.python-version }}"

      - name: Install test dependencies
        run: uv sync --no-dev --group ${{ matrix.toxenv }}

      - name: Install system dependencies
        run: sudo apt install -y gettext

      - name: Build and run tests
        run: |
          make npm_requirements
          make build
          make test
          uv run make validate_translations
